[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API requests to the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5000
  publish = "dist/public"
  autoLaunch = true

[functions]
  node_bundler = "esbuild"